version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: air-quality-db
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - airquality_data_container:/data/db

  api: 
    build: .
    container_name: air-quality-api
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/air-quality
    depends_on:
      - mongodb

volumes:
  airquality_data_container:
