version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: yassir-air-quality-db
    ports:
      - 27027:27017
    volumes:
      - yassir_airquality_data_container:/data/db

  api: 
    build: .
    container_name: yassir-air-quality-api
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/yassir-air-quality
    depends_on:
      - mongodb

volumes:
  yassir_airquality_data_container:
